version: "3"
services:
  backend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ./AdLerBackend.API/config:/app/config # Default location für config Datei
#      - wwwroot:/app/wwwroot # 
volumes:
    wwwroot: