version: "3"
services:
  backend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_URLS: "https://+:;http://+:"
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_ENVIRONMENT: "Production"